### ISSUE TITLE
Formattig is not working

### ISSUE THREAD

**Issue by Taymindis** [nginxinc/crossplane#56]
```bash 
crossplane format -o new.conf -t /etc/nginx/nginx.conf
Traceback (most recent call last):
  File "/usr/local/bin/crossplane", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/crossplane/__main__.py", line 228, in main
    func(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/crossplane/__main__.py", line 130, in format
    output = build_file(parsed, indent, tabs) + '\n'
NameError: name 'build_file' is not defined
```

**Comment by aluttik** [comment]
Ah shoot, I'm on it.

**Comment by aluttik** [comment]
@Taymindis I just pushed a fix and uploaded it to PyPI. The format command should work now in the current version (0.4.14). Try updating with `pip install -U crossplane`.

**Comment by Taymindis** [comment]
It works now! Great!
